declare module 'sgeo' {
  /** Declaration file generated by dts-gen */

  export class latlon {
    constructor(lat: number, lon: number)

    lat: number
    lng: number

    bearingRadTo(point: latlon): number

    bearingTo(point: latlon): number

    destinationPoint(brng: number, dist: number): latlon

    distanceRadTo(point: latlon): number

    distanceTo(point: latlon, precision?: number): number

    finalBearingTo(point: latlon): number

    interpolate(point: latlon, num: number): latlon[]

    lat(format?: string, dp?: number): number

    lon(format?: string, dp?: number): number

    midpointTo(point: latlon): latlon

    rhumbBearingTo(point: latlon): anumberny

    rhumbDestinationPoint(brng: number, dist: number): latlon

    rhumbDistanceTo(point: latlon): number

    rhumbMidpointTo(point: latlon): latlon

    toString(format?: string, dp?: number): string

    static intersection(p1: latlon, brng1: number, p2: latlon, brng2: number): latlon
  }

  export function midpoint(points: latlon[]): latlon

  export function parseDMS(dmsStr: string): number

  export function toBrng(deg: number, format?: string, dp?: number): string

  export function toDMS(deg: number, format?: string, dp?: number): string

  export function toLat(deg: number, format?: string, dp?: number): number

  export function toLon(deg: number, format?: string, dp?: number): number
}
