const normFactor = require('./normFactor.js')
module.exports.normFactor = normFactor
module.exports.nF = normFactor
module.exports.geo = require('./geo.js')
module.exports.events = require('./events.js')
module.exports.segments = require('./segments.js')
module.exports.points = require('./points.js')
module.exports.waypoints = require('./waypoints.js')
module.exports.courses = require('./courses.js')
